### ISSUE TITLE
[feature suggestion] nmb4

### ISSUE THREAD

**Issue by BamsyTheSergal** [dstmnaki/My-Public-E2-Repository#1]
would be cool if a hand or leg piece got removed/destroyed that arm stopped working or it flopped down like a fish.

and another cool thing if you could individually control both main arms, like if i wanted to have a sword on one, and a shield on the other, i could raise one and use the other

**Comment by BamsyTheSergal** [comment]
@dstmnaki i hope i am not bothering to much

**Comment by dstmnaki** [comment]
Ouh no i was actually wondering if answering in gmail would work or not as
i'm not logged in to my github on phone and couldn't be bothered to get on
my pc lmao

Now about the features, those will be covered in nmb5 i'm already working
on a near complete recreation of armored core "ac" mech base, left mouse
button uses left hand, right for right hand, i just can't think of good
buttons for back units as q and e are kinda taken...

**Comment by BamsyTheSergal** [comment]
i have been mainly just using numpad and a pod controller for now, but it would help to have individual hand movement for a double barrel shotgun idea i have been doing lol

**Comment by dstmnaki** [comment]
Yeah i got that in the next base

**Comment by dstmnaki** [comment]
If you know how to code tho, you can change the arms to go up separately,
it was originally like that in the code, i just changed a single thing to
make them both go up at the same time

**Comment by BamsyTheSergal** [comment]
ah i see, lol

**Comment by BamsyTheSergal** [comment]
i kinda got another "suggestion" if you will, its more so inspiration, there is this mecha anime thingy, and it's exo suit system is really neat, especially how they do the guns, they are basically using 20mm guns as normal ones humans would use, this is their offical website for reference art,

https://project-obsolete.com/en/exoframe/

**Comment by derpoman** [comment]
Quickboosts mainly and maye different leg types /biped/reverse joint/ quad leg
I REALLY love this base and i await the next version with excitement
Any updates on progress you could give ?

Also Upper body only version to make Tank mechs

**Comment by dstmnaki** [comment]
The next version has boosting that replaces running, quick boosting/dodging
will be added once i find a good button for it

**Comment by BamsyTheSergal** [comment]
you could make it use a wire numpad lol

**Comment by dstmnaki** [comment]
It's not that, i just can't think of a good key to press for dodge, maybe
control or something

**Comment by derpoman** [comment]
Settings to change the resting position of the arms (preferably individually) Cuz if you wanna use longer guns it just drives it into the ground
and maybe a separate Ik arm e2 to allow weapon two handing (to make titanfall mechs!)

**Comment by BamsyTheSergal** [comment]
i think in the original version (currently uploaded) can do that, just is a lil goofy to do

**Comment by dstmnaki** [comment]
Nah the original didn't have neither, and idk if i will update this anymore

**Comment by derpoman** [comment]
maybe for the next chip make sprinting toggleable with ctrl, and then put QB in shift, also if it's gonna have an EN system maybe have it be able to change the energy consumption of the different actions so if ppl want to make like an MT you can just have it very low EN and regen and also drain a lot when jumping, and not as much when on ground
